include_directories(SYSTEM deps/asio/asio/include)
include_directories(SYSTEM deps/boost/asio/include)
include_directories(SYSTEM deps/boost/assert/include)
include_directories(SYSTEM deps/boost/config/include)
include_directories(SYSTEM deps/boost/core/include)
include_directories(SYSTEM deps/boost/hana/include)
include_directories(SYSTEM deps/boost/intrusive/include)
include_directories(SYSTEM deps/boost/move/include)
include_directories(SYSTEM deps/boost/static_assert/include)
include_directories(SYSTEM deps/boost/system/include)
include_directories(SYSTEM deps/boost/throw_exception/include)
include_directories(SYSTEM deps/json/single_include)
include_directories(SYSTEM deps/lager)
include_directories(SYSTEM deps/websocketpp)
include_directories(SYSTEM deps/zug)

add_subdirectory(deps/JUCE)
