include_directories(SYSTEM deps/boost/asio/include)
include_directories(SYSTEM deps/boost/assert/include)
include_directories(SYSTEM deps/boost/bind/include)
include_directories(SYSTEM deps/boost/config/include)
include_directories(SYSTEM deps/boost/core/include)
include_directories(SYSTEM deps/boost/date_time/include)
include_directories(SYSTEM deps/boost/hana/include)
include_directories(SYSTEM deps/boost/intrusive/include)
include_directories(SYSTEM deps/boost/move/include)
include_directories(SYSTEM deps/boost/mpl/include)
include_directories(SYSTEM deps/boost/numeric_conversion/include)
include_directories(SYSTEM deps/boost/predef/include)
include_directories(SYSTEM deps/boost/preprocessor/include)
include_directories(SYSTEM deps/boost/regex/include)
include_directories(SYSTEM deps/boost/smart_ptr/include)
include_directories(SYSTEM deps/boost/static_assert/include)
include_directories(SYSTEM deps/boost/system/include)
include_directories(SYSTEM deps/boost/throw_exception/include)
include_directories(SYSTEM deps/boost/utility/include)
include_directories(SYSTEM deps/boost/type_traits/include)
include_directories(SYSTEM deps/json/single_include)
include_directories(SYSTEM deps/lager)
include_directories(SYSTEM deps/websocketpp)
include_directories(SYSTEM deps/zug)

add_subdirectory(deps/JUCE)
